### ISSUE TITLE
Website is down.. 504

### ISSUE THREAD

**Issue by lipis** [k0kubun/githubranking#19]

**Comment by k0kubun** [comment]
Oh that's true.....
The contract of my database server has been expired. Since I have backup, I'll restore data tonight.
Thank you for reporting.

**Comment by k0kubun** [comment]
Now it's operational. Sorry for the trouble.

**Comment by lipis** [comment]
What about the outdated data?! Would you sync them all?

**Comment by k0kubun** [comment]
I surely want to do until this month is over.

**Comment by lipis** [comment]
just press the buttons.. and do that often :)

**Comment by k0kubun** [comment]
I'm very thankful for you to use this service :sob:
